### ISSUE TITLE
install electron on raspberry pi 3

### ISSUE THREAD

**Issue by wilsonandusa** [augustogoncalves/personal-assistant#1]
hi, how did you install electron on raspberry pi 3?

**Comment by rogercorrea** [comment]
It is problem for me also. I don't see as you installed Electron in your project. In project description you talk about NodeJS but not Electron.

**Comment by wilsonandusa** [comment]
@rogercorrea I think after you install NodeJS and npm in raspberry pi 3, you can run electron projects.

**Comment by rogercorrea** [comment]
@wilsonandusa Now is integrated, so... because a long time ago I tried install but was using the "electron for Raspberry pi" and doesn't worked. 

I will try! Thanks!

**Comment by augustogoncalves** [comment]
Electron is one of the packages used, but by that time was the 0.16 version, now they have a newer version.
